# -*- coding: utf-8 -*-
"""TNC_Python_Projesi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15biKTirw79nAijaVo-lA1zg1JvJ191ML
"""

import os

gorevler = []

DOSYA_ADI = "gorevler.txt"

def dosyadan_oku():
    """Görevleri dosyadan okur"""
    global gorevler
    try:
        if os.path.exists(DOSYA_ADI):
            with open(DOSYA_ADI, 'r', encoding='utf-8') as dosya:
                gorevler = [satir.strip() for satir in dosya.readlines() if satir.strip()]
            print(f" {len(gorevler)} görev dosyadan yüklendi.")
        else:
            print(" Henüz kaydedilmiş görev bulunamadı. Yeni bir liste oluşturulacak.")
    except Exception as e:
        print(f"Dosya okuma hatası: {e}")

def dosyaya_kaydet():
    """Görevleri dosyaya kaydeder"""
    try:
        with open(DOSYA_ADI, 'w', encoding='utf-8') as dosya:
            for gorev in gorevler:
                dosya.write(gorev + '\n')
        print(" Görevler kaydedildi.")
    except Exception as e:
        print(f" Dosya kaydetme hatası: {e}")

def gorevleri_listele():
    """Mevcut görevleri listeler"""
    print("\n" + "="*40)
    print(" GÖREV LİSTESİ")
    print("="*40)

    if not gorevler:
        print("Henüz hiç görev eklenmemiş.")
    else:
        for index, gorev in enumerate(gorevler, 1):
            print(f"{index}. {gorev}")

    print("="*40 + "\n")

def gorev_ekle():
    """Yeni görev ekler"""
    print("\n- YENİ GÖREV EKLE -")
    gorev = input("Görev metni girin: ").strip()

    if not gorev:
        print("Hata: Boş görev eklenemez!")
        return

    gorevler.append(gorev)
    print(f" Görev eklendi: '{gorev}'")
    dosyaya_kaydet()

def gorev_duzenle():
    """Mevcut bir görevi düzenler"""
    print("\n--- GÖREV DÜZENLE ---")

    if not gorevler:
        print(" Düzenlenecek görev bulunamadı.")
        return

    gorevleri_listele()

    try:
        secim = int(input("Düzenlemek istediğiniz görevin numarasını girin: "))

        if secim < 1 or secim > len(gorevler):
            print(" Hata! Geçersiz görev numarası!")
            return

        yeni_gorev = input("Yeni görev metni girin: ").strip()

        if not yeni_gorev:
            print(" Hata! Boş görev girişi yapılamaz!")
            return

        eski_gorev = gorevler[secim - 1]
        gorevler[secim - 1] = yeni_gorev
        print(f" Görev güncellendi:")
        print(f"  Eski: '{eski_gorev}'")
        print(f"  Yeni: '{yeni_gorev}'")
        dosyaya_kaydet()

    except ValueError:
        print(" Hata: Lütfen geçerli bir sayı girin!")

def gorev_sil():
    """Bir görevi siler"""
    print("\n - GÖREV SİL -")

    if not gorevler:
        print(" Silinecek görev bulunamadı.")
        return

    gorevleri_listele()

    try:
        secim = int(input("Silmek istediğiniz görevin numarasını girin: "))

        if secim < 1 or secim > len(gorevler):
            print(" Hata: Geçersiz görev numarası!")
            return

        silinen_gorev = gorevler.pop(secim - 1)
        print(f" Görev silindi: '{silinen_gorev}'")
        dosyaya_kaydet()

    except ValueError:
        print(" Hata: Lütfen geçerli bir sayı girin!")

def menu_goster():
    """Ana menüyü gösterir"""
    print("\n" + "="*24)
    print(" TO-DO LIST UYGULAMASI")
    print("="*24)
    print("1. Görevleri Listele")
    print("2. Yeni Görev Ekle")
    print("3. Görev Düzenle")
    print("4. Görev Sil")
    print("5. Çıkış")
    print("="*24)

def main():
    """Ana program döngüsü"""
    print("\n To-Do List Uygulamasına Hoş Geldiniz!")
    print("-" * 40)

    dosyadan_oku()

    while True:
        menu_goster()

        secim = input("\nSeçiminiz (1-5): ").strip()

        if secim == '1':
            gorevleri_listele()
        elif secim == '2':
            gorev_ekle()
        elif secim == '3':
            gorev_duzenle()
        elif secim == '4':
            gorev_sil()
        elif secim == '5':
            print("\n Çıkış yapılıyor... Hoşçakal!")
            break
        else:
            print("\n Hata! Geçersiz seçim! Lütfen 1-5 arasında bir sayı girin.")

        input("\nDevam etmek için Enter'a basın...")

if __name__ == "__main__":
    main()